/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as ContributeScriptJson } from "../Contribute.ral.json";
import { default as RefundScriptJson } from "../Refund.ral.json";
import { default as WithdrawScriptJson } from "../Withdraw.ral.json";

export const Contribute = new ExecutableScript<{
  pool: HexString;
  amount: bigint;
}>(Script.fromJson(ContributeScriptJson, "", []), getContractByCodeHash);

export const Refund = new ExecutableScript<{ pool: HexString }>(
  Script.fromJson(RefundScriptJson, "", []),
  getContractByCodeHash
);

export const Withdraw = new ExecutableScript<{ pool: HexString }>(
  Script.fromJson(WithdrawScriptJson, "", []),
  getContractByCodeHash
);
