-- CreateTable
CREATE TABLE "Pool" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "contractAddress" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT 'Poolname'
);

-- CreateTable
CREATE TABLE "AlphPrice" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "priceInUsd" REAL NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
